spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/xcydone?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 345678

logging:
  config: classpath:logback-spring.xml

hehe:
  haha: BILL_INTER_TAXBAL_${latn_id}-${yyyymm}\d{2}-\d+.txt
  haha2: BILL_INTER_TAXBAL_{latn_id}-{yyyymm}\d{2}-\d+.txt

mail:
  host: smtp.qq.com
  username: 1641265515@qq.com
  password: sgfskdleeajhfdbi
  filePath: E:/dataSource/
