spring:
  profiles:
    active: local

server:
  port: 8099
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations:
    classpath: mapper/*.xml
  typeAliasesPackage: com.xcydone.hello.springexam.entity
  configuration:
    map-underscore-to-camel-case: true
