spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.128.10.40:3306/batch_test?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&characterEncoding=utf8
    username: gw
    password: gw123!@#

logging:
  config: classpath:logback-spring.xml

log:
  level: debug
  path: ./logs

sftp:
  ip: 132.126.3.46
  port: 23
  username: test
  password: 12345678
  ttss:
    tempfilepath: F:\downLoadFile2\
    sourcefilepath: /ttss
    prefix: BILL_INTER_TAXBAL_${latn_id}-${yyyymm}\d{2}-\d+.txt
    isSingleFile: 1

ftp:
  ip: 132.126.3.46
  port: 21
  username: test
  password: 12345678
  ttss:
    tempfilepath: F:\downLoadFile2\
    sourcefilepath: /ttss
    prefix: BILL_INTER_TAXBAL_${latn_id}-${yyyymm}\d{2}-\d+.txt
    isSingleFile: 1