server:
  port: 8092
  servlet:
    context-path: /

dubbo:
  application:           #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: Customer
    id: Customer
  registry:               #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://xcydtwo:2181,xcydthree:2181,xcydfour:2181,xcydfive:2181
  scan:
    base-packages: com.crossyf.dubbo.*
  consumer:
    check: false
    timeout: 300000

spring:
  http:
    multipart:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 345678
    url: jdbc:mysql://127.0.0.1:3306/xcydone?characterEncoding=utf8&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root

swagger:
  basePackage: com.crossyf.dubbo
  title: 系统文档api
  description: 系统文档api描述
  version: 1.0.0
  enable: true

isInterceptor: false

# 加密secret
jwt:
  secret: ojbkqOMwYE31y5aea8SkoVee3q
# 默认过期30分钟，单位：秒
  expire-second: 1800

minio:
  endpoint: http://192.168.81.213:12000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test

hbase:
  connectKey: hbase.zookeeper.quorum
  connectValue: xcydtwo:2181,xcydthree:2181,xcydfour:2181,xcydfive:2181
  nameSpace: fs.defaultFS
  defaultPath: hdfs://myha01/hbase224