server:
  port: 8094
  servlet:
    context-path: /dubbo-server

spring:
  application:
    name: dubbo-server
  profiles.active: local

mybatis-plus:
  mapper-locations:
    classpath: mapper/**/*.xml
  typeAliasesPackage: com.crossyf.dubbo.*.entity
  configuration:
    map-underscore-to-camel-case: true